spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 请填写本机密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password:
      database: 0
      timeout: 3000ms

app:
  jwt:
    secret: ${JWT_SECRET}
    expire-minutes: 120
